Print error in Wasm runner (#1323)
Error is now shown in Diagnostic section

```
Diagnostics:
  pulumi:pulumi:Stack (failure-test):
    ../../target/release/pulumi_gestalt_wasm_runner run "../../target/wasm32-wasip2/release/pulumi_gestalt_example_failure.wasm"
    thread '<unnamed>' panicked at examples\failure\src\lib.rs:5:1:
    called `Result::unwrap()` on an `Err` value: Failed to run main function
    Caused by:
        Important error message
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    Error: error while executing at wasm backtrace:
        0:  0x13887 - pulumi_gestalt_example_failure.wasm!abort
        1:   0x7ced - pulumi_gestalt_example_failure.wasm!std::sys::pal::wasip2::helpers::abort_internal::h4d8504fa71998c67
        2:   0x4c73 - pulumi_gestalt_example_failure.wasm!std::process::abort::h60c0b5ae545e222b
        3:   0x4c69 - pulumi_gestalt_example_failure.wasm!__rustc[5224e6b81cd82a8f]::__rust_abort
        4:   0x9595 - pulumi_gestalt_example_failure.wasm!__rustc[5224e6b81cd82a8f]::__rust_start_panic
        5:   0x9125 - pulumi_gestalt_example_failure.wasm!__rustc[5224e6b81cd82a8f]::rust_panic
        6:   0x90a3 - pulumi_gestalt_example_failure.wasm!std::panicking::rust_panic_with_hook::h3c7ab64d423dbbd2
        7:   0x8018 - pulumi_gestalt_example_failure.wasm!std::panicking::begin_panic_handler::{{closure}}::h81e867bd663cda03
        8:   0x7f79 - pulumi_gestalt_example_failure.wasm!std::sys::backtrace::__rust_end_short_backtrace::h3293be7771749058
        9:   0x8a32 - pulumi_gestalt_example_failure.wasm!__rustc[5224e6b81cd82a8f]::rust_begin_unwind
       10:  0x150ca - pulumi_gestalt_example_failure.wasm!core::panicking::panic_fmt::h2c2561e995cb7188
       11:  0x16a58 - pulumi_gestalt_example_failure.wasm!core::result::unwrap_failed::hbca36ead248bdfdb
       12:   0x1e03 - pulumi_gestalt_example_failure.wasm!component:pulumi-gestalt/pulumi-main@0.0.0-DEV#main
    Caused by:
        wasm trap: wasm `unreachable` instruction executed
    error: Recipe `run` failed on line 7 with exit code 1

    error: an unhandled error occurred: 'C:\Users\andrz\AppData\Local\Microsoft\WinGet\Packages\Casey.Just_Microsoft.Winget.Source_8wekyb3d8bbwe\just.exe just run' exited with non-zero exit code: 1

```

Closes #1283